# Generated by Django 5.1.4 on 2026-09-06 05:24

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=200)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['type', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='EntityChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changed_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='graph.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EntityEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rel', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='graph.entity')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='graph.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=64)),
                ('predicate', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='engine.workflowdef')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'type'], name='graph_entit_tenant__a72576_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attrs'], name='idx_entity_attrs_gin'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('tenant', 'type', 'external_id'), name='uniq_entity_tenant_type_extid'),
        ),
        migrations.AddIndex(
            model_name='entitychange',
            index=models.Index(fields=['processed_at', 'created_at'], name='graph_entit_process_c96fde_idx'),
        ),
        migrations.AddIndex(
            model_name='entitychange',
            index=models.Index(fields=['tenant', 'entity_type'], name='graph_entit_tenant__c40850_idx'),
        ),
        migrations.AddIndex(
            model_name='entityedge',
            index=models.Index(fields=['tenant', 'src', 'rel'], name='graph_entit_tenant__8feb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='entityedge',
            index=models.Index(fields=['tenant', 'dst', 'rel'], name='graph_entit_tenant__fea6c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityedge',
            constraint=models.UniqueConstraint(fields=('tenant', 'src', 'rel', 'dst'), name='uniq_edge'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['tenant', 'entity_type', 'enabled'], name='graph_trigg_tenant__d78bda_idx'),
        ),
    ]
