# Generated by Django 5.1.4 on 2026-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='input_template',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
