# Generated by Django 5.1.4 on 2026-09-06 07:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_trigger_input_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['type', 'external_id'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='entitychange',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='entityedge',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='entity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entitychange',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entityedge',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trigger',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
