# Generated by Django 5.1.4 on 2026-09-06 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('spec', models.JSONField()),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPENSATING', 'Compensating'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('entity_ref', models.CharField(blank=True, default='', max_length=200)),
                ('trigger_source', models.CharField(default='api', max_length=100)),
                ('error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='engine.workflowdef')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('RUN_STARTED', 'Run Started'), ('STEP_SCHEDULED', 'Step Scheduled'), ('STEP_STARTED', 'Step Started'), ('STEP_SUCCEEDED', 'Step Succeeded'), ('STEP_FAILED', 'Step Failed'), ('STEP_RETRY_SCHEDULED', 'Step Retry Scheduled'), ('TIMER_SET', 'Timer Set'), ('TIMER_FIRED', 'Timer Fired'), ('COMPENSATION_STARTED', 'Compensation Started'), ('STEP_COMPENSATED', 'Step Compensated'), ('RUN_SUCCEEDED', 'Run Succeeded'), ('RUN_FAILED', 'Run Failed'), ('RUN_CANCELLED', 'Run Cancelled')], max_length=32)),
                ('step_id', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='engine.run')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['run_id', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='engine_rune_run_id_a472e9_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='uniq_runevent_run_seq')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('EXECUTE', 'Execute'), ('COMPENSATE', 'Compensate')], default='EXECUTE', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('LEASED', 'Leased'), ('DONE', 'Done')], default='READY', max_length=16)),
                ('run_after', models.DateTimeField()),
                ('lease_owner', models.CharField(blank=True, default='', max_length=200)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='engine.run')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['run_after'],
                'indexes': [models.Index(fields=['tenant', 'status', 'run_after'], name='engine_task_tenant__f767de_idx'), models.Index(fields=['status', 'lease_expires_at'], name='engine_task_status_4318e8_idx'), models.Index(fields=['run', 'step_id'], name='engine_task_run_id_9e9fc3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowdef',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'version'), name='uniq_workflowdef_tenant_name_version'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='engine_run_tenant__6a8700_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['tenant', 'entity_ref'], name='engine_run_tenant__fb40b6_idx'),
        ),
    ]
