# Generated by Django 5.1.4 on 2026-09-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runevent',
            name='type',
            field=models.CharField(choices=[('RUN_STARTED', 'Run Started'), ('STEP_SCHEDULED', 'Step Scheduled'), ('STEP_STARTED', 'Step Started'), ('STEP_SUCCEEDED', 'Step Succeeded'), ('STEP_FAILED', 'Step Failed'), ('STEP_RETRY_SCHEDULED', 'Step Retry Scheduled'), ('TIMER_SET', 'Timer Set'), ('TIMER_FIRED', 'Timer Fired'), ('COMPENSATION_STARTED', 'Compensation Started'), ('STEP_COMPENSATED', 'Step Compensated'), ('COMPENSATION_FAILED', 'Compensation Failed'), ('RUN_SUCCEEDED', 'Run Succeeded'), ('RUN_FAILED', 'Run Failed'), ('RUN_CANCELLED', 'Run Cancelled')], max_length=32),
        ),
    ]
