# Generated by Django 5.1.4 on 2026-09-06 07:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_runevent_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='runevent',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['run_id', 'seq']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['run_after']},
        ),
        migrations.AlterModelOptions(
            name='workflowdef',
            options={'base_manager_name': 'all_tenants', 'default_manager_name': 'objects', 'ordering': ['name', '-version']},
        ),
        migrations.AlterModelManagers(
            name='run',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='runevent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflowdef',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
